# Generated by Django 3.1.2 on 2022-11-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
